### PR TITLE
Remove `engine` constraints in package.json

### PR DESCRIPTION
**Pull request by roschaefer**
I had a quick look into the documentation of these constraints: https://docs.npmjs.com/files/package.json#engines
Regarding the `npm` constraints they say:
> this field is advisory onlyreasoning

so even they are not really confident on the usefulness of the constraints for `npm`. Can we just be optimistic and assume it works fine? If people get back to us with problems we can still add a constraint if we *know*  there are any issues.

I cannot see anything in the code of this package that would justify having these constraints.

This commit makes #20 obsolete.

If I missed anything here I would love if you could inform me about why we have the constraints at all.

### CODE REVIEW

**Comment by arthurvasconcelos** [comment]
Fixed at 98ef214d6b77f2666b878f23735cb07b6b27ed53 :)

**Comment by roschaefer** [comment]
Wow! Dependencies udpated, node engine constraints removed, cypress tests added and even stories for vue storybook. I love it, I love it I :heart: it! Thank you so much @arthurvasconcelos 

I love it

One question: Is there a build server already?

**Comment by arthurvasconcelos** [comment]
@roschaefer build server? What exactly you mean?

**Comment by roschaefer** [comment]
I can't see an automated build setup:
Screenshot - 2019-08-25T003700 404

A build server is great. It not only proves that there is automated builds (and probably tests). It helps potential contributors like me to get a single-source-of-truth about how the package should be built. E.g. when I removed the node engines constraints earlier, I was not aware that I broke the build.

With a build server you understand what are the minimum checks before your PR gets "mergeable". Also, you learn the last time when this package was built successfully. When I consider to contribute to a package, the latest build server log is one of the first things I check out before I start.

**Comment by arthurvasconcelos** [comment]
@roschaefer oh ok, now I got it. Yeah, I am not using Travis or Circle because as GH invited me to beta test GH Actions that what I am using.

I am still improving on it, as new service, documentation as a whole can still improve.

Screenshot from 2019-08-26 11-09-57
Screenshot from 2019-08-26 11-11-18

If you have any knowledge with GH Actions I am accepting help with it, you can check the current pipeline configuration [here](https://github.com/arthurvasconcelos/vue-izitoast/blob/master/.github/workflows/ci.yml).

Also, PR will now be tested by GH Actions, so this will prevent breaking changes without knowing.

**Comment by roschaefer** [comment]
@arthurvasconcelos Ok :ok_hand: so the only suggestion I have is to put a badge into the `README.md` for the ignorant contributors (like me) who never used Github Actions before. It should say sth. like "build" so contributors looking for a build server are just one click away from it (well they are, because they could also click on the "actions" tab but who knows).

So, searching for "Github actions badge" showed me this: https://github.com/Atrox/github-actions-badge

**Comment by arthurvasconcelos** [comment]
@roschaefer oh great! I will be handling this over the course of this week! I am also fairly new to GH Actions and didn't know that someone implemented a badge! =D Good to know!

Also over the course of this week, I will be moving GH Pages to a separate branch once I will automate it and clean npm releases that will also be automated! =D

I am thinking maybe in creating a zenhub or some other kind of board so that ease the conversation =D

**Pull request closed without merging**
